### ISSUE TITLE
Wish: add //go:generate comments to generated files

### ISSUE THREAD

**Issue by twpayne** [kyleconroy/sqlc#147]
...for compatibility with [`go generate`](https://blog.golang.org/generate) which will make sqlc easier to integrate into existing Go builds.

sqlc looks really really good - thank you for this project!

**Comment by kyleconroy** [comment]
@twpayne what additional support would you like to see? The following comment in a (non-generated) Go file works today

```
package foo

//go:generate sqlc generate
```

**Comment by twpayne** [comment]
I've always tried to put the `//go:generate` comment in the generated file itself, rather than in a separate non-generated file. My reasoning is that this provides more transparency: it's immediately obvious which files are generated and what command generated them.

**Comment by kyleconroy** [comment]
> it's immediately obvious which files are generated and what command generated them

The [go generate](https://golang.org/pkg/cmd/go/internal/generate/) docs suggest a different mechanism for determining which files are generated. Each generated file should have a comment that matches the regex `^// Code generated .* DO NOT EDIT\.$`. sqlc adheres to this pattern and adds `// Code generated by sqlc. DO NOT EDIT.` to every source file.

Adding the go:generate comment to the file itself will not work because sqlc must be run at the root of the directory. For most users the generated files live in sub-directories.

I'm happy with the current state of support in my above comment.

**Comment by twpayne** [comment]
Agreed :) Thank you for considering the request and for your work on this fanastic package :)
