### ISSUE TITLE
Installation errors "go install"

### ISSUE THREAD

**Issue by nakem1** [kyleconroy/sqlc#1473]
### Version

1.12.0

go version go1.17.5

### What happened?

../vendor/github.com/pganalyze/pg_query_go/v2/parser/parser.go:6:10: fatal error: pg_query.h: No such file or directory
 #include "pg_query.h"
                ^~~~~~~~~~~~

### What operating system are you using?

macOS(darwin/amd64)

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
I notice you're using Go 1.12. Building sqlc requires Go >= 1.16. Once you've upgraded to that version, let me know if you're still seeing this bug

**Comment by kyleconroy** [comment]
Oops, after reading this again, 1.12 is the sqlc version.

What version of Go are you using?

**Comment by zmitry** [comment]
same for me 
go 1.17

**Comment by flicaflow** [comment]
I'm seeing the same problem after I tried to vendor my dependencies. Reason seems to be that the include sub-folder below parser does not make it into the vendor tree. 
Are you vendor as well?

This issue explains it https://github.com/golang/go/issues/26366  .  
Solution from the sqlcs end would be to move the .h files in the parser package instead of having them in the include folder which apparently gets dropped because there are no go files in it. Also putting a dummy go file in the include dir could work (don't know if that needs to get used to not be dropped by vendoring).

**Comment by ryanrolds** [comment]
The [instructions on the module with the vendoring issue](https://github.com/pganalyze/pg_query_go?tab=readme-ov-file#usage-with-go-modules) resolved it for me.
