### ISSUE TITLE
Differences from xo/xo

### ISSUE THREAD

**Issue by dvn0** [kyleconroy/sqlc#154]
I discovered this project yesterday and think it looks great. Someone pointed out https://github.com/xo/xo, which seems very similar.

I'm curious as to whether you evaluated this `xo` as well, and what the differences with `sqlc` might be.

**Comment by euller88** [comment]
Hi, I've used `xo` before using `sqlc`, and I can say that the difference is in how you design your applications. If you already have a database up and running, with other applications accessing it, then `xo` is the best choice. If you are creating the database from scratch, then `sqlc` is onne of your best choices, since it gives you much more freedom to play with your data.

**Comment by kyleconroy** [comment]
I'm working on writing up a larger set of documentation comparing sqlc to the other Go ORMs (for lack of a better word). That won't be done for a bit, so here's a short answer. Keep in mind that I've never used xo in production. I've only read through the documentation. Please correct me if something in this explanation is wrong.

First off, xo is a more mature project and supports a much wider range of databases. sqlc currently only supports PostrgreSQL.

xo generates its code by reading the schema from a running database instance. sqlc parses the schema from DDL statements in SQL files. Whether that's a plus or a minus depends on personal preferences.

xo pairs the parsed schema with a set of [query templates](https://github.com/xo/xo/tree/master/templates). You can add custom templates if you need additional queries. sqlc requires that you write out every query you need. It does not generate default methods for you to use.

The best answer is to compare the generated code for xo's `booktest` example. Using [this schema](https://github.com/xo/xo/blob/master/examples/booktest/postgres/schema.sql), xo will generate an ORM that can be used like this: [main.go](https://github.com/xo/xo/blob/master/examples/booktest/postgres/main.go).

I've ported that example to sqlc. I first had to write the [nine queries](https://github.com/kyleconroy/sqlc-examples/blob/master/booktest/query.sql) automatically generated by xo. The code ended up looking about the same: [main.go](https://github.com/kyleconroy/sqlc-examples/blob/master/booktest/main.go).

Lastly, sqlc catches errors in your SQL queries. I don't know if xo will catch errors in query templates.

**Comment by llimllib** [comment]
In case anybody else ends up here, the `sqlc-examples` repo has been deleted, and the example now appears to live in the [`/examples` dir of the main `sqlc` repository](https://github.com/kyleconroy/sqlc/tree/master/examples/booktest)

**Comment by coolaj86** [comment]
Here's the update XO Booktest:
- schema: https://github.com/xo/xo/blob/master/_examples/booktest/sql/postgres_schema.sql
- query: https://github.com/xo/xo/blob/master/_examples/booktest/sql/postgres_query.sql
- generated code: https://github.com/xo/xo/tree/master/_examples/booktest/postgres
- example use: https://github.com/xo/xo/blob/master/_examples/booktest/postgres.go

I have a hard time following it to understand how it's being used.

It looks like you don't so much write the queries as it generates the queries from indexes in the database.

`sqlc` seem to be a bit more grug-brain-friendly, though I'd love to see an example of "this is where xo really shines" so that I'm not stuck comparing apples to oranges (they don't seem so similar to me from what I can gather briefly looking through the xo docs).
