### ISSUE TITLE
Couchbase flavor

### ISSUE THREAD

**Issue by zdebra** [kyleconroy/sqlc#163]
Hello, first of all - I love this approach. I was sold after seeing the first few lines of the readme. This solves a lot of problems that I am facing a lot while developing persistent layers for web applications in golang.

I would like to contribute with the support of the Couchbase database. Is it something that you are open to? I've created this issue to prevent unnecessary PR rejection 🙂

**Comment by euller88** [comment]
Isn't Couchbase a NoSQL database?

**Comment by kyleconroy** [comment]
@zdebra thanks for feature request

sqlc won't be able to add support for Couchbase. While it does have a SQL-like query language ([Nickel](https://www.couchbase.com/products/n1ql)), data stored in Couchbase buckets do not have a consistent schema across documents. This means that, quoting the [Nickel query tutorial](https://query-tutorial.couchbase.com/tutorial/#2):

> Remember that there is no schema in Couchbase. N1QL is flexible enough to return all results that match your query, even if they vary in structure.

Since the structure isn't known ahead of time, sqlc can't generate a struct for the return type.

**Comment by zdebra** [comment]
@kyleconroy How does a lack of the schema is a problem for generating data layer code? 

You have to assume that nobody else would insert a document that would violate expected structure of documents. But that is what you have to assume for relational databases as well - your database schema might be changed from a different source than generated code.

The generated code would be in charge of all of the writes/reads to the Couchbase in my use-case. You can even see it as a virtual schema that is guaranteed by the application.

Is there something that I am missing? I am fine if this is not something you would like to support, but I don't see any technical or philosophical reasons why it can't be done.

Thank you.
