### ISSUE TITLE
Can't override with type in same package

### ISSUE THREAD

**Issue by mightyguava** [kyleconroy/sqlc#177]
I wanted to create a type for an enum, e.g. `State`

```sql
# job.sql
create table job (
  id bigserial primary key,
  state int
)
```

```go
# job.sql.go
type Job struct {
  ID string `json:"id"`
  State State `json:"state"`
}
```

```go
# enums.go
type State string
const (
  StateRunning State = iota
  StateFailed
  StateDone
)
```

It's convenient to have `enums.go` in the same package as the generated code, but there doesn't seem to be a way to tell the generator to not create an import. I end up with the package importing itself which Go reports as an import cycle.

**Comment by alibitek** [comment]
Indeed, for some reason the enum type is set as the struct field type in some cases. 
Don't know exactly why. 
I tried to set an override, but unfortunately I can't, because the enum from db is generate in the same package as the code using it.

**First test**:   
```
        {
          "go_type": "gitlab.com/company/project/database.ECustomEnum",
          "db_type": "e_custom_enum"
        }
```
this gives error: `import cycle not allowed` , because the package where the code is generated, namely: `database` is trying to import itself via the override.  

**Second test**:  
```
        {
          "go_type": "gitlab.com/company/project/ECustomEnum",
          "db_type": "e_custom_enum"
        }
```
this gives error: `cannot load gitlab: cannot find module providing package gitlab` 
Inside `querier.go` I get a weird import like:  
```
import (
   "context"
   "github.com/google/uuid"
   "gitlab"
)
```

**Comment by kyleconroy** [comment]
This should now on main. You'll need to specify the `go_type` using an object instead of just a string

```json
        {
          "go_type": {"type": "ECustomEnum"},
          "db_type": "e_custom_enum"
        }

```
