### ISSUE TITLE
Moving the SQL Parser to a publicly available pkg

### ISSUE THREAD

**Issue by collinforsyth** [kyleconroy/sqlc#1793]
### What do you want to change?

Would you ever consider moving the parsing/tokenizing of the SQL AST to a package that other Go libraries could use? This is a much better API than the `pg_query_go` provides

I'd be happy to help out with the work if you would consider it.

**Comment by kyleconroy** [comment]
My usual answer here is no. The internal packages are kept private so that they can be refactored without impact others.

That said, can you elaborate a bit on the specific parts you'd like packaged up? sqlc doesn't do any of its own parsing. The AST package was based on a older version of the pg_query_go AST package.
