### ISSUE TITLE
Support tern migration files

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#1824]
### What do you want to change?

[Tern](https://github.com/JackC/tern), from the creator of pgx, is a new migration tool. It's migration files are SQL files, but use a different delimiter than golang-migrate.

```
create table t1(
  id serial primary key
);

---- create above / drop below ----

drop table t1;
```

**Comment by skabbes** [comment]
I think it is really good to support both the "tried and true" and the cutting edge migration systems, especially since I'd consider sqlc cutting edge itself.

That said, it will always be a game of whack-a-mole to support them all, I've been using:

```
pg_dump --no-privileges --no-acl --no-owner --schema-only --no-comments --encoding=utf8 MY_DB_URI
```

Then I use that schema.sql file to feed to sqlc.  The database I manage has 957 migrations, and I think a source of truth schema file is a best practice anyway.

Perhaps we can publish (in the docs) that kind of workaround for anyone with an exotic migration system?

The workflow would be:
```
1. `your_migration_tool up` # to a dev database
1. `pg_dump ...`
1. `sqlc generate`
```

🤷 it works for me, maybe useful for others too.

**Comment by kyleconroy** [comment]
Turns out this is already supported as of https://github.com/kyleconroy/sqlc/pull/286

> Perhaps we can publish (in the docs) that kind of workaround for anyone with an exotic migration system?

We could add that to this documentation page https://docs.sqlc.dev/en/stable/howto/ddl.html
