### ISSUE TITLE
Avoid downtime when dropping a column

### ISSUE THREAD

**Issue by ericmeter** [kyleconroy/sqlc#1844]
### What do you want to change?

Let's say I have a table like
```
CREATE TABLE foo (
  id   BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL
);
```
And I have a query like:
```
-- name: GetFoo :many
SELECT * FROM foo;
```
Resulting in a generated query like:
```
const getFoo = `-- name: GetFoo :many
SELECT id, name FROM foo`
```
If I then want to drop a column from `foo`, say, `name` - and I run a database migration to do so (`ALTER TABLE foo DROP COLUMN name;`), sqlc will correctly recognize that `getFoo` has changed to:

```
const getFoo = `-- name: GetFoo :many
SELECT id FROM foo`
```
... but the code deployed into production is still running the old query `SELECT id, name FROM foo`.

**Question: is there a way to avoid downtime in between the time the migration runs until when the deployment of my application is complete?** (i.e. how do I avoid a `pq: column "name" does not exist` error in this example?).

I could run the migration after the new code deploys, but standardizing the deployment process to run migrations prior to starting the application is strongly preferred (and in cases where we are adding new columns/tables, required to avoid similar downtime). Having different migration flows based on the migration type is difficult and fragile to manage.

I see mention of this issue in the comment section of this Hacker News topic (https://news.ycombinator.com/item?id=28466871) but I didn't see a concrete suggestion for how to resolve.

Thank you!

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by ericmeter** [comment]
One more thing I could do is just stop using `SELECT *` and always explicitly list out the fields in the queries in the `.sql` files. Just wondering if there's a different way to do it. Thank you!

**Comment by kyleconroy** [comment]
There's a clever way to solve this. I can't remember who initially came up with it, but it works really well.

Instead of having all your database migrations in a single folder, create two. The new folder is your migration staging area. These are the migrations that you're planning on running.

You'd add the migration that drops the column in this folder and re-run sqlc generate. The queries no longer use the column, but it still exists. 

Deploy this version of the code. Now you can move the stages migration into the main folder, deploy the migration, and drop the column.

Hope that helps!

**Comment by ericmeter** [comment]
Thank you - this is very helpful!

Note for others who may stumble across this thread: Create the folder and add it (in addition to the main migrations folder) to the `packages.schema` list in `sqlc.yaml`:

Example:
```
packages:
...
    schema:
      - "./db/migrations"
      - "./db/migrations/staging"
      ...
```
