### ISSUE TITLE
View support

### ISSUE THREAD

**Issue by maxhawkins** [kyleconroy/sqlc#193]
```sql
CREATE TABLE foo (bar INT);

CREATE VIEW baz AS
  SELECT *
  FROM foo;
```

Should generate:
```go
type Foo struct {
  Bar int
}
type Baz struct {
  Bar int
}
```

Currently no structs are generated for views.

**Comment by ereyes01** [comment]
I just found this package and it looks super useful. One of the first things I did was to search the issues to see if there was any insight on how views are handled, and found this.

Is the DDL code given ever actually run in the database? If it's only used to generate the structs, would a valid workaround be:

```sql
CREATE TABLE foo (bar INT);

CREATE TABLE baz (bar INT);
```

And then design your queries of `baz` as normal, since the DDL is only for deriving and generating the `Baz` Go struct?

I acknowledge that it's not as convenient or robust as copy/pasting the same thing you run in the database, and sometimes it's extra work to determine the equivalent `CREATE TABLE` command from a complex view query.

Thanks!

**Comment by kyleconroy** [comment]
@ereyes01 That's a good work around for the time being. The eventual goal is to fully support view creation and querying.

**Comment by randomlogin** [comment]
Hi!
I'm using 1.5.0, am I right, that views are not supported there yet? 
The only workaround is to construct appropriate table?

**Comment by ScottyFillups** [comment]
Hi @kyleconroy! Really love sqlc; I'm wondering if there's any plans to tackle views any time soon? I'd willing to help out :smiley:
