### ISSUE TITLE
UUID type override only applies to primary keys

### ISSUE THREAD

**Issue by owenoclee** [kyleconroy/sqlc#208]
Hello, I'm seeing some unexpected behaviour with type overriding. Steps to reproduce below.

`sqlc.json` with overrides as follows:
```
"overrides": [
  {
    "go_type": "github.com/segmentio/ksuid.KSUID",
    "postgres_type": "uuid"
  }
]
```

Run `sqlc generate` on the following:
```
CREATE TABLE posts (
	id UUID PRIMARY KEY,
	user_id UUID,
	body TEXT
);

-- name: GetPosts :many
SELECT id, user_id, body FROM posts;
```

The generated `models.go` ends up with a mix of `ksuid.KSUID` and `uuid.UUID`:
```
type Posts struct {
	ID     ksuid.KSUID
	UserID uuid.UUID
	Body   sql.NullString
}
```

**Comment by kyleconroy** [comment]
This is confusing, but currently working as intended. The reason `UserID` isn't overridden is because it's possible that it's NULL. To override both columns, your `sqlc.json` file should look like this:

```
"overrides": [
  {
    "go_type": "github.com/segmentio/ksuid.KSUID",
    "postgres_type": "uuid"
  },
  {
    "go_type": "github.com/segmentio/ksuid.KSUID",
    "postgres_type": "uuid",
    "null": true
  },
]
```

What we should probably do it have a setting where you can pick if the override applies to `NULL`, `NOT NULL`, or both. It feels like both should be the default, but many custom types do not handle NULL correctly. In your case, `ksuid.KSUID` appears to handle NULL.
