### ISSUE TITLE
Timestamps silently lose their time zones

### ISSUE THREAD

**Issue by sgielen** [kyleconroy/sqlc#2117]
### Version

1.16.0

### What happened?

I insert dates with time zones into the database like this:

```
	timeZone := time.FixedZone("CET", 3600)
	date := time.Date(2020, time.January, 1, 0, 0, 0, 0, timeZone)

	log.Printf("****** registering date = %s ********", date.String())
	if err := q.RegisterDate(ctx, date); err != nil {
		log.Fatal(err)
	}
```

Then, I retrieve them:

```
	dates, err := q.GetRegisteredDates(ctx)
	if err != nil {
		log.Fatal(err)
	}

	for _, date := range dates {
		log.Printf("******** read date = %s ********", date.Date.String())
	}
```

This outputs:

```
2023/02/27 16:03:45 ****** registering date = 2020-01-01 00:00:00 +0100 CET ********
2023/02/27 16:03:45 ******** read date = 2020-01-01 00:00:00 +0000 UTC ********
```

Note how the printed time is the same, but the time zone is different.

Now, the column type is `TIMESTAMP`, as opposed to `TIMESTAMP WITH TIME ZONE`, so I expect the time zone to be gone. However, I do expect the absolute moment in time to be the same, but because the time zone is simply lost, the moment in time is not the same. So, I would expect the output to be:

```
2023/02/27 16:03:45 ****** registering date = 2020-01-01 00:00:00 +0100 CET ********
2023/02/27 16:03:45 ******** read date = 2019-12-31 23:00:00 +0000 UTC ********
```

This way, the two times reflect the same moment in time, as if calling `.UTC()` on the time object just before passing it to the generated `q.RegisterDate` function. Should this not be done automatically, because sqlc knows that the column has no time zone support?

A tiny test case is attached, which uses `github.com/fergusstrange/embedded-postgres` to run.

### Database schema

```sql
CREATE TABLE dates (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	date TIMESTAMP NOT NULL
);
```

### SQL queries

```sql
-- name: RegisterDate :exec
INSERT INTO dates (date) VALUES ($1);

-- name: GetRegisteredDates :many
SELECT id, date FROM dates;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "queries.sql"
    schema: "schema.sql"
    gen:
      go:
        out: "gendb"
        sql_package: "pgx/v4"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by skabbes** [comment]
I think this is a misunderstanding of the `timestamp` postgres type.  That type stores a "wall clock" time - meaning that whenever you query it (no matter what timezone you are in) it will give the same result.  And `timestamptz` type converts to UTC before storing.

So, despite the terrible naming of these type - they do not do what you think.

If you want to keep the timezone, then use a `timestamp` column, and a `timezone` column next to it.  Or if you want everything converted to UTC first, then use `timestamptz`.


Maybe this post clears it up for you?
https://medium.com/building-the-system/how-to-store-dates-and-times-in-postgresql-269bda8d6403

**Comment by sgielen** [comment]
@skabbes Ah, that makes sense, thank you! Sorry for the noise :-)

I indeed interpreted [the documentation](https://www.postgresql.org/docs/current/datatype-datetime.html) incorrectly, thinking that `TIMESTAMP WITH TIME ZONE` (`TIMESTAMPTZ`) stores a timezone, while `TIMESTAMP WITHOUT TIME ZONE` (`TIMESTAMP`) stores as UTC. But, as the post you linked notes, both types do not actually store any time zone (also shown by the fact that they have the same size); `TIMESTAMP` ignores the time zone on write, and `TIMESTAMPTZ` converts to UTC on write.

Indeed, if I change the code to insert one date in CET and one date in UTC, `TIMESTAMP` behaves as follows:

```
2023/02/27 20:04:19 ****** registering date = 2020-01-01 00:00:00 +0100 CET ********
2023/02/27 20:04:19 ****** registering date = 2020-02-01 00:00:00 +0000 UTC ********
2023/02/27 20:04:19 ******** read date = 2020-01-01 00:00:00 +0000 UTC ********
2023/02/27 20:04:19 ******** read date = 2020-02-01 00:00:00 +0000 UTC ********
```

If I use a `TIMESTAMPTZ` type instead of `TIMESTAMP`, the time zone is taken into account when writing, but (slightly surprising to me) the information is returned in local time instead of UTC:

```
2023/02/27 20:09:15 ****** registering date = 2020-01-01 00:00:00 +0100 CET ********
2023/02/27 20:09:15 ****** registering date = 2020-02-01 00:00:00 +0000 UTC ********
2023/02/27 20:09:15 ******** read date = 2020-01-01 00:00:00 +0100 CET ********
2023/02/27 20:09:15 ******** read date = 2020-02-01 01:00:00 +0100 CET ********
```

According to https://github.com/jackc/pgx/issues/520 this conversion to local time is actually done by the client, not PostgreSQL itself. This can be confirmed by setting `time.Local = time.UTC` before reading the dates back, in which case they will be UTC. But that's definitely outside of the scope of sqlc, so I'm closing this :-)

**Comment by skabbes** [comment]
In case useful to anyone else...

The rule of thumb I use is this:

`created_at`, `updated_at` etc timestamps are always `timestamptz` since they refer to instants in time.

Any type of future scheduled event that is meant to be attended by a human, or to be observed by a human - I store as a `timestamp` column + a `timezone TEXT` column.  Because if (god forbid) the timezone changes definition (like [Mexico](https://www.theguardian.com/world/2022/oct/27/mexico-votes-abolish-summer-time-daylight-savings) just did) your scheduled events can still happen at the "right" time.  Or in case the user changes timezone (maybe they moved, or on a business trip), you can possibly update it to the correct.

This of course depends on your use case, but I have found it to be a useful rule of thumb.

Since I am also a Javascript developer, this library's API actually helped me understand all the complexities of time.
https://tc39.es/proposal-temporal/docs/

**Comment by sgielen** [comment]
> Any type of future scheduled event that is meant to be attended by a human, or to be observed by a human - I store as a `timestamp` column + a `timezone TEXT` column.

Then I suppose it is also smart to set the `timezone` column to the user's location (e.g. `Europe/Amsterdam`) and not the timezone itself (`CET`/`CEST`). Otherwise, if the location changes timezone (e.g. the British army takes Amsterdam by force and changes its timezone). In the case of Golang this may be possible with `.Location().String()`. Do you do it this way as well, or do you have different thoughts?

**Comment by skabbes** [comment]
> Then I suppose it is also smart to set the timezone column to the user's location

Ah yes - that's what I meant, maybe I just mixed up the terminology, it needs to be a location-based timezone from [pg_timezone_names](https://www.postgresql.org/docs/current/view-pg-timezone-names.html) view. For example, my timezone / location is `America/Phoenix`.  This corresponds 1-1 with MST (since Phoenix does not observe daylight savings time), but my neighbors to the north `America/Denver` flip flop between MST and MDT twice a year.

Nothing is truly future-proof if you're talking about something unfortunately political like "what time is it here".  In the case of a foreceful takeover of Amsterdam, I think it would be wise to expose the timezone name in the UI.  So no matter what, the time is not ambiguous (I'm sure there will be "Amsterdammers" who refuse to comply with the new time convention).

So: 
"The meeting is at 11:15AM (America/Phoenix)" (unambiguous) 
or
"Reports will be emailed to you daily at 11:15AM (MST)" (even though this says MST, it is still unambiguous to the user)

**In order to expose it like that, you need to have it stored**

> Then I suppose it is also smart to set the timezone column to the user's location 

Maybe this is pedantic, but I wouldn't say the "user's" timezone necessarily - if you're representing an in-person meeting with a video-call option -  I would store the _meeting's_ timezone (and I would also show it, and optionally convert to the user's local time, as a convenience for the digital attendees). This also goes for any collaboratively scheduled event.
 
The last thing I'll say about timezones is I think they should _always_ be user-configurable.  You can best-effort detect what location-timezone a user is currently in, but some people live in areas where there are multiple "local times". This will be true for any commuter near a timezone line - their ouse is _technically_ in the US/Central time zone, but they work, go to school, and all their friends liv in US/Eastern.  So I might choose to live my life in a different timezone that what my lat/lng says I technically should be. 

**That's why I think your timezone-location should be auto-detected, but always user-configurable.**

**Comment by sgielen** [comment]
Thanks a lot for your insights @skabbes. Working with dates, times and time zones is never easy, there's always an edge case and as you say nothing is truly future-proof, but with these insights it has become a bit easier for me (perhaps & other readers) to implement it as close to correct as possible.

**Comment by skabbes** [comment]
There is a lot more reading to do with regard to timezones from people a lot smarter than me, but happy to share the bit of experience I do have on this topic.
