### ISSUE TITLE
Test for enum membership

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#447]
An enum type in Postgres generates the following Go code:

```sql
CREATE TYPE company_role AS ENUM ('member', 'admin', 'guest');
```

```go
type CompanyRole string

const (
	CompanyRoleMember CompanyRole = "member"
	CompanyRoleAdmin  CompanyRole = "admin"
	CompanyRoleGuest  CompanyRole = "guest"
)
```

Given a random string, I would like to test whether it is a member of the enum or not without going to the database. I can create a function, but `s == CompanyRoleMember || s == CompanyRoleAdmin || s == CompanyRoleGuest` breaks without warning as soon as a new field was added to the enum.

Is there a way to provide a map, or `func ValidCompanyRole(s string) bool` or `func (c CompanyRole) Valid() bool`, or anything I could call to automatically check for enum membership?

**Comment by kyleconroy** [comment]
> Is there a way to provide a map, or func ValidCompanyRole(s string) bool or func (c CompanyRole) Valid() bool,

sqlc could generate this function, but so far I've erred on the side of generating less code rather than more code.

The closest example I could find is the generated enum code for protocol buffers, which generates two static maps for conversion between strings and ints. However, I think they only do that because enums in protocol buffer land are mapped to int32.

So I think I'm happy with the code we generate today, since the function you're looking for isn't too difficult to write by hand.
