### ISSUE TITLE
Bazel build files

### ISSUE THREAD

**Issue by mmcloughlin** [kyleconroy/sqlc#479]
It would be nice if this project could provide bazel build files.

I've been struggling to build the `sqlc` binary with bazel/gazelle. I'm likely to give up and just use the release binaries, but I thought I'd file an issue to record the difficulties.

The main challenge is `cgo`: build fails with `com_github_lfittl_pg_query_go/parser/parser.go:6:10: fatal error: pg_query.h: No such file or directory`. Making this work with bazel is apparently possible but non-trivial, and would require special bazel build files either in `sqlc` or `pg_query_go`.

The following file also causes problems for `gazelle`, since it references a fake pacakge:

https://github.com/kyleconroy/sqlc/blob/3d3630a6b526e2e2c0649b7c405b56c5935de754/internal/endtoend/testdata/mysql_overrides/go/models.go#L9

Again, not high priority since the release binaries provide a workaround.

**Comment by kyleconroy** [comment]
@mmcloughlin thanks for the bug report.

Since I don't use Bazel to build sqlc, it's unlikely that I'll add build files. However, I'd be happy to do it if it's easy to maintain.

I'm surprised gazelle is having issues with that Go file, as it's in a testdata directory. I just did a bit of research and found https://github.com/bazelbuild/bazel-gazelle/issues/456. I'll fix that Go code to be buildable.

You'll need to open an issue with https://github.com/lfittl/pg_query_go, though the project seems pretty dead at the moment.

**Comment by mmcloughlin** [comment]
Thanks for the response and quick fix.

Feel free to close this if you want, I created this issue mainly to save people a bit of time if they are googling for it in future.

**Comment by shiwano** [comment]
This issue is closed, but it's just a comment for people who came here via a search engine. To be exact, this problem is not a `sqlc` package's, but it's a `pg_query_go` package's, so I think `sqlc` should not provide a BUILD file.

https://github.com/bazelbuild/rules_go/issues/2957#issuecomment-924952595

As described in the above comment, the cause is that the all C files used by the `pg_query_go/parser` package are not in the same directory. `rules_go` and `Gazelle` expect that file structure when they build a Go package in Bazel. 

As a work-around, it would be better to create a patch file and set it to the `go_repository` rule of the `pg_query_go` like bellow:

```patch
diff --git a/parser/BUILD.bazel b/parser/BUILD.bazel
index bd914fb79..b7ee39fe4 100644
--- a/parser/BUILD.bazel
+++ b/parser/BUILD.bazel
@@ -87,7 +87,8 @@ go_library(
     ],
     cgo = True,
     clinkopts = [""],
-    copts = ["-Iparser/include -g -fstack-protector -std=gnu99"],
+    copts = ["-Iexternal/com_github_pganalyze_pg_query_go_v2/parser/include -g -fstack-protector -std=gnu99"],
+    cdeps = [":include"],
     importpath = "github.com/pganalyze/pg_query_go/v2/parser",
     importpath_aliases = ["github.com/pganalyze/pg_query_go/parser"],
     visibility = ["//visibility:public"],
@@ -98,3 +99,8 @@ alias(
     actual = ":parser",
     visibility = ["//visibility:public"],
 )
+
+cc_library(
+    name = "include",
+    hdrs = glob(["include/**"]),
+)
```

```python
    go_repository(
        name = "com_github_pganalyze_pg_query_go_v2",
        importpath = "github.com/pganalyze/pg_query_go/v2",
        sum = "h1:LiNm3WoBV/cc144X6jlVKD5DPL+fI2wfvCXT7z25B8U=",
        version = "v2.1.2",
        # +++++++++++++++++++++++
        patch_args = ["-p1"],
        patches = ["//:created_patch_file.patch"],
    )
```
