### ISSUE TITLE
:exec need return sql.Result

### ISSUE THREAD

**Issue by digitive** [kyleconroy/sqlc#524]
Hi,

Can we make `:exec` return not only the error but also the sql.Result please? Because we want to retrieve LastInsertId() or RowsAffected()

So below generate code
```
const createAuthor = `-- name: CreateAuthor :exec
insert into authors(name) values (?)
`
func (q *Queries) CreateAuthor(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createAuthor, name)
	return err
}
```

can be 
```
const createAuthor = `-- name: CreateAuthor :exec
insert into authors(name) values (?)
`
func (q *Queries) CreateAuthor(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAuthor, name)
}
```

**Comment by kyleconroy** [comment]
> Because we want to retrieve LastInsertId() or RowsAffected()

You can use `:execrows` to get the rows affected. I understand that having the `Result` is especially helpful for MySQL, which doesn't support `RETURNING`.

There are two ways this can be implemented. A configuration option or a new command type. The configuration option would be `emit_result_for_exec`, but that honestly feels a bit heavy handed. Since we already have `:exec` and `:execrows`, probably better just to create a third one.

Do you have any opinions on the name of that option? I'm thinking `:execresult` or just `:result`

**Comment by digitive** [comment]
Hi Kyleconroy,

Thanks for your comments. Yes I prefer a new command type, which should be easier to implement. IMO just `:result` will be good enough.

**Comment by tooolbox** [comment]
I think `:execresult` is better as it's more obvious and consistent.
