### ISSUE TITLE
FR: sqlc is not compatible with existing models

### ISSUE THREAD

**Issue by landbed** [kyleconroy/sqlc#589]
our project already have models and both models are almost same.

1, add configuration to using old models and skip generating models?

2, add configuration to generating files to different folder?

**Comment by kyleconroy** [comment]
Thanks for the feature request!

Right now, sqlc owns the models that it generates. I understand that this makes it difficult to integrate into existing projects. Sadly, with limited development bandwidth, solving this issue is low priority. I'd like to solve it eventually, but I want to be honest that it's not going to be any time soon. Sorry!
