### ISSUE TITLE
Name conflict in generated code

### ISSUE THREAD

**Issue by amckinney** [kyleconroy/sqlc#748]
I am writing a new table that contains enums, and encountered a naming conflict in the generated code.

For example,
```
CREATE TYPE role AS ENUM ('write', 'read');

CREATE TABLE roles (
  id           UUID                    PRIMARY KEY DEFAULT gen_random_uuid (),
  create_time  TIMESTAMPTZ             NOT NULL    DEFAULT CURRENT_TIMESTAMP,
  update_time  TIMESTAMPTZ             NOT NULL    DEFAULT CURRENT_TIMESTAMP,
  role         role                    NOT NULL,
);
```

With this, a `Role` type is generated for _both_ the `role` enum, as well as the entries in the `roles` table, so the code won't compile.

Is there any way to override this behavior? I noticed that we can [rename struct fields ](https://github.com/kyleconroy/sqlc#renaming-struct-fields), but it's unclear if this is possible at the table-level.

**Comment by kyleconroy** [comment]
I've reproduced this [here](https://play.sqlc.dev/p/929f7a6a997221cb620b231ab9fb63b23e19cba27063fe205e9eb872a1447ac9)

**Comment by kyleconroy** [comment]
Possible duplicate of #588

**Comment by amckinney** [comment]
> Possible duplicate of #588

Yeah, this is likely, since both are generating the singular form of an otherwise plural name (i.e. the `roles` table generates a `role`).

**Comment by coolaj86** [comment]
Why was this closed?

As far as I can tell, there's no solution, and no workaround for _this_ case.

The only way this can be solved with the current config, if I understand correctly, is that the database schema itself _MUST_ be changed - because both `role` and `roles` are treated as `Roles`, right?

So even trying to map either `role` to `RoleEnum` or `roles` to `RolesTable` would result in _both_ identifiers being targeted, right?

P.S. for the onlookers coming here from search results, #588 has a few different workarounds for similar cases that may also work in your case.
