### ISSUE TITLE
dynamic limit, ordering

### ISSUE THREAD

**Issue by mh-cbon** [kyleconroy/sqlc#84]
how to deal with dynamic limit and ordering ? in my memories those arguments can t be prepared; thus a regular variable, like a condition statement uses, will trigger error.

**Comment by euller88** [comment]
You mean this?:
```sql
-- name: OrderAuthorsById :many
SELECT * FROM authors
ORDER BY id
LIMIT $1;
```

**Comment by mh-cbon** [comment]
yes. especially, for ORDER clause. for limit, maybe it is engine dependent can 't remember for sure.

**Comment by euller88** [comment]
Well I don't think this problem is within the scope of this package. [This thread on the Postgres mailing list](https://www.postgresql-archive.org/ORDER-BY-in-prepared-statements-td5834944.html#none) has some details on the matter.
It appears that prepared statements receive values, while the ORDER clause receives identifiers. So apparently, it is not possible to have dynamic values for the ORDER clause.

**Comment by kyleconroy** [comment]
@euller88 is correct. sqlc supports parameterized limits, but can not support parameterized ordering.
